### PR TITLE
Improve configuration for braille-outputting scripts

### LINKED ISSUE #198: improve configuration for braille-outputting scripts
In these cases, the job submission process will be two steps: submit the content and then after the engine analyzes the content, set some options. 

See https://github.com/daisy/pipeline/issues/750

Also relevant: https://daisy-dev.slack.com/archives/C064GB8U9/p1708360756773949

### LINKED ISSUE #207: Hide "transform" option of dtbook-to-pef, html-to-pef and epub3-to-pef scripts
In the context of [improving the configuration for braille-outputting scripts](https://github.com/daisy/pipeline-ui/issues/198), it would be better to hide the "transform" option, at least until we find a better user interface for the option.  

The option has the same query syntax as the "stylesheet-parameters" option ([which we are eliminating also](https://github.com/daisy/pipeline-ui/issues/198)), and isn't super user friendly. [Documentation](http://daisy.github.io/pipeline/Get-Help/User-Guide/Braille/) is available, but more targeted at advanced users.

It should be fine to drop the option from the GUI, because

- It is already partially covered by the "braille-code" option
- If needed, the *braille transcription* and *hyphenation* related features of the braille transformation (which are almost always the only parts) can be controlled also through a `@text-transform` rule in the CSS.

For now the option will stay available on the command line (like the "stylesheet-parameters" option).

### PR DESCRIPTION
**Pull request by NPavie**
This pull request modify braille outputting scripts (ending in `to-pef`)  to use the new `stylesheet-parameters` endpoint as to complete and/or simplify the scripts settings by relying on user stylesheets.

Closes #198 
Closes #207

### CODE REVIEW

**Comment by NPavie** [comment]
Ok i forgot to test some things at first before making the PR but it should now be fixed.

The new UX is as following
- On braille outputting script, the form is first limited to input, stylesheet, page width and height
- A next button performs a preliminary form validation, checking if input is set.

The ui expects a `stylesheetParameters` with additionnal or modified script options to switch to the second page of the form.

- If no stylesheet is provided, an empty array is returned in this field, and the remaining default script options are displayed
- If a stylesheet is provided, the new endpoint is used to retrieve the parameters value, stored the result in the job `stylesheetParameters` field, and
  - on parameters that are already defined in the script, the job request is updated with the new default value
  - on new parameters, those parameters are converted to new options added to the job request
  - The script options that are used to compute the Script form UI is updated by merging the script options with the  `stylesheetParameters` content
- A new button "Back" let the user go back to first page of the form to change input or initial options

**Comment by bertfrees** [comment]
I'm not sure if I fully understand, but I will find out by testing it. Will do that as soon as possible.

**Comment by bertfrees** [comment]
The Windows build failed: https://github.com/daisy/pipeline-ui/actions/runs/8618713899/job/23621741796. I guess this is because of the bug you reported.

**Comment by bertfrees** [comment]
I was able to fix the build: https://github.com/daisy/pipeline-ui/actions/runs/8628429754

**Comment by bertfrees** [comment]
@NPavie Testing it now. It does not seem to work when an input XML is given (with a `style` element in its `head`), but no style sheets. Is that because of a bug in the engine, or is it because of the UI?

**Comment by bertfrees** [comment]
Other observations:
- When I set the style sheets option to "https://raw.githubusercontent.com/daisy/pipeline-modules/master/scripts/html-to-pef/src/main/resources/css/_definition-lists.scss", the next button does not do anything. When I set it to a local file that includes `@import url(https://raw.githubusercontent.com/daisy/pipeline-modules/master/scripts/html-to-pef/src/main/resources/css/_definition-lists.scss);`, it does work. Not sure whether this is an issue in the engine or UI.
- The "_definition-lists.scss" style sheet gives me 3 options:
  - Group dt dd
  - Dt suffix
  - Dt separator
 
  These are auto-generated nice-names. Obviously the descriptions would be better if the Sass variables would have Doxygen comments. What is surprising to me is that the expanded description of these options is "Definition lists" in the three cases. I've spotted a bug in the engine that explains this.

**Pull request merged**
