### PR TITLE
Allow building the UI including the engine with a single command, and automate with Github workflows

### PR DESCRIPTION
**Pull request by bertfrees**
Done:

- [x] Makefile to build engine
- [x] Workflow for macOS
- [x] Workflow for Windows

Not included (yet):

- [ ] Sign artefacts
- [ ] Publish artefacts on releases page

### CODE REVIEW

**Comment by bertfrees** [comment]
I was able to setup a workflow that build the DMG and EXE files. For now I have tested it by uploading the files as workflow artifacts. E.g. you can see and download them from [this page](https://github.com/daisy/pipeline-ui/actions/runs/3658252168) (at the bottom).

I've temporarily made the workflow trigger when new commits are pushed to this PR, but the idea is to only do it when tags are pushed. Eventually we could automatically publish the files on the release page of the tag.

What I'd like to do before we merge the PR is to also let Github perform the code-signing. For macOS, I was planning to following these steps: https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development. @rdeltour Have you had a chance to look at that page and does it seem secure enough for you?

@Nico @marisademeglio Will it be possible to do this for Windows too, or will that take us too far? From the email you forwarded it seems Daniel has done the signing of the previous releases.

**Comment by danielweck** [comment]
Hi Bert, I only signed the Windows binary (I am the current custodian of the physical USB token that contains Daisy's private code-signing key / certificate).
I was not needed for Apple code-signing and notarizing.

**Comment by bertfrees** [comment]
Hi Daniel. Thanks for confirming. So for every release we need to reach out to you with the request to sign the files? Or do you think it makes sense we try to automate it somehow?

**Comment by danielweck** [comment]
I believe there are alternative solutions for EV certificate provisioning (perhaps Microsoft's own developer / cloud platform), but access to Daisy's current code signing cert is secured via a physical USB token. I am the current holder but I didn't purchase / I am not the account holder (you need to ask the US Fund For Daisy manager).

**Comment by rdeltour** [comment]
> What I'd like to do before we merge the PR is to also let Github perform the code-signing. For macOS, I was planning to following [these steps](https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development). @rdeltour Have you had a chance to look at that page and does it seem secure enough for you?

Yes I did look at the doc; the process is secured by Github secrets, I'm no expert but it seems secure enough for our needs!

**Pull request merged**
